name: face-detection
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel 
confinement: strict

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  
environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: title="glxgears"
  
apps:
  camera: 
    command: xwayland-kiosk-launch $SNAP/run_camera
    plugs: 
    - camera
    - desktop
    - opengl
    - wayland
    - network-bind


  video: 
    command: xwayland-kiosk-launch $SNAP/run_video
    plugs: 
    - camera
    - desktop
    - opengl
    - wayland


parts:
  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]


  my-app:
    plugin: python
    source: ./src
    build-packages:
      - python3-pip
    stage:
      - -usr/bin/f2py
    stage-packages:
      - python3.7
    python-packages:
      - pip
      - Image
    override-build: |
      set -x

      WHEEL_FILE='tensorflow==2.0.0b0'
      echo arch is $SNAPCRAFT_ARCH_TRIPLET
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "arm-linux-gnueabh" ]
      then
      WHEEL_FILE='https://github.com/lhelontra/tensorflow-on-arm/releases/download/v2.0.0/tensorflow-2.0.0-cp37-none-linux_armv7l.whl'
      fi

      PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL python3 -m pip install -I $WHEEL_FILE

      find $SNAPCRAFT_PART_INSTALL

      snapcraftctl build



  opencv-python:
    #after: [tensorflow]
    source: https://github.com/skvark/opencv-python.git
    source-type: git
    source-tag: '34'
    plugin: python
    python-version: python3
    build-packages:
    - python3.7
    - libssl-dev
    - python-setuptools
    - qt4-default
    stage-packages: 
    - python3.7
    - libaudio2
    - libjbig0
    - libjpeg-turbo8
    - libqt4-test
    - libqtcore4
    - libqtgui4
    - libtiff5
    - libblas3
    - libblas-dev
    - python-scipy
    - gcc 
    - gfortran 
    - python-dev
    - liblapack-dev 
    - python-pip
    - cython
    python-packages:
      - pip
      - Cython
      - numpy==1.18.3
      - scikit-build
      - utils
  


  static:
    plugin: dump
    source: ./static
