name: face-detection
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel 
confinement: strict

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  
environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: title="glxgears"
  XWAYLAND_I3_CONFIG_FILE: $SNAP_DATA/i3.config
  PYTHONPATH: $SNAP/usr/lib/python3.6/site-packages


plugs:
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11
  
apps:
  face-detection: 
    command: $SNAP/run_camera
    plugs: 
    - camera
    - desktop
    - desktop-legacy
    - x11-plug
    - opengl
    - wayland
    - network-bind
    - network-control
    - mount-observe
    


  daemon: 
    command: run-daemon xwayland-kiosk-launch $SNAP/run_camera
    daemon: simple
    plugs: 
    - camera
    - desktop
    - opengl
    - wayland
    - network
    - network-bind
    - network-control
    - mount-observe
    - x11-plug
    slots: [ x11 ]

plugs:
  x11-plug: # because cannot have identical plug/slot name in same yaml.
    interface: x11


parts:
  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl pulseaudio wayland

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, i3status, libegl1-mesa, libgl1-mesa-glx ]


  my-part:
    plugin: python
    source: ./src
    python-version: python3
    override-build: |
      snapcraftctl build

      WHEEL_FILE=./wheels/tensorflow-2.2.0-cp36-cp36m-linux_x86_64.whl
      cat ${WHEEL_FILE}.* > $WHEEL_FILE
      PYTHONUSERBASE=$SNAPCRAFT_PART_INSTALL python3 -m pip install -I $WHEEL_FILE
      
    build-packages: 
      - python3
      - mesa-utils
      - pkg-config
      - libcairo2-dev
      - libsystemd-dev
      - system-config-printer
      - python-cups
      - python3-dev
      - git
      - virtualenv
      - build-essential
      - libdbus-glib-1-dev
      - libgirepository1.0-dev
      - libcups2-dev
    stage-packages:
      - libavahi-client3
      - libavahi-common3
      - libcairo-gobject2
      - libcairo2
      - libcups2
      - libfontconfig1
      - libfreetype6
      - libgirepository-1.0-1
      - libice6
      - libpixman-1-0
      - libpng16-16
      - libsm6
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxrender1
      - python3-numpy
      - libblas3

    python-packages: 
      #- numpy==1.18.3
      - opencv-python==4.2.0.34
      - Pillow==7.0.0
      - protobuf==3.12.0
  
  scripts:
    plugin: dump
    source: ./src
    stage:
      - '*.py'
      - 'model'
      - 'protos'
      - run_camera
      - run_video
